// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUWgRm4wVkFobZrrc7pwyCoJHDoCyaK94',
    appId: '1:485257279019:web:2ff68da6403f45d18bdc6e',
    messagingSenderId: '485257279019',
    projectId: 'learn-firebase-cli-87f39',
    authDomain: 'learn-firebase-cli-87f39.firebaseapp.com',
    storageBucket: 'learn-firebase-cli-87f39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwMyHFvS8o1g77jn5tTfTUqwIqvBe64nI',
    appId: '1:485257279019:android:8299e0cfe3edb1d78bdc6e',
    messagingSenderId: '485257279019',
    projectId: 'learn-firebase-cli-87f39',
    storageBucket: 'learn-firebase-cli-87f39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbCw3b3L08hqN14AYaOJyaxg9FoRY01OQ',
    appId: '1:485257279019:ios:baaf3312c307c02b8bdc6e',
    messagingSenderId: '485257279019',
    projectId: 'learn-firebase-cli-87f39',
    storageBucket: 'learn-firebase-cli-87f39.appspot.com',
    iosClientId: '485257279019-svsencpec1jfoc4fbo405amd1jq4lt0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFirebaseCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbCw3b3L08hqN14AYaOJyaxg9FoRY01OQ',
    appId: '1:485257279019:ios:baaf3312c307c02b8bdc6e',
    messagingSenderId: '485257279019',
    projectId: 'learn-firebase-cli-87f39',
    storageBucket: 'learn-firebase-cli-87f39.appspot.com',
    iosClientId: '485257279019-svsencpec1jfoc4fbo405amd1jq4lt0i.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFirebaseCli',
  );
}
